################################# Default configuration ###################
# https://www.gohugo.org/doc/overview/configuration/
baseURL = "https://xiak.com"
theme = "xiak-hugo"
title = "XIAK | Community"
themesDir = "../.."
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# language
hasCJKLanguage = true
DefaultContentLanguage = "zh"
disableLanguages = ["en"]
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
pygmentsUseClasses = true
canonifyURLs = false

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "100px"
# Meta data
description = "Xiak's Blog"
author = "Xiak"
# Contact Information
mobile = "0"
email = "x@xiak.com"
location = "China"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

################################ Chinese Language ########################
[Languages.zh]
languageName = "中文"
languageCode = "zh"
contentDir = "content/zh"
weight = 1
# copyright
copyright = "Copyright &copy; 2021 XIAK 保留所有权利"

######################### Chinese navigation #############################
# main menu
[[Languages.zh.menu.main]]
name = "主页"
URL = "/"
weight = 1

[[Languages.zh.menu.main]]
weight = 5
name = "博客"
hasChildren = true

  [[Languages.zh.menu.main]]
  parent = "博客"
  name = "算法"
  URL = "algorithm"

  [[Languages.zh.menu.main]]
  parent = "博客"
  name = "Kubernetes"
  URL = "kubernetes"

[[Languages.zh.menu.main]]
name = "联系我"
URL = "contact"
weight = 6

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
# copyright
copyright = "Copyright &copy; 2021 XIAK All Rights Reserved"


######################### English navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
weight = 5
name = "Blog"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Blog"
  name = "Algorithm"
  URL = "algorithm"

  [[Languages.en.menu.main]]
  parent = "Blog"
  name = "Kubernetes"
  URL = "kubernetes"

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 6